name: 'drill4j-report-github-action'
description: 'Report test-coverage by Drill4J'
branding:
  icon: info
  color: blue
inputs:
  group_id:
    description: "Group ID"
    required: true
  agent_id:
    description: "Agent ID"
    required: true
  current_branch:
    description: "Current branch"
    required: true
  current_vcs_ref:
    description: "Current VCS reference"
    required: true
  base_branch:
    description: "Base branch"
    required: true
  base_vcs_ref:
    description: "Base VCS reference"
    required: true
  drill_address:
    description: "Port of Drill address"
    required: true
  repo_token:
    description: "Github Token"
    required: true
  mode:
    description: "Mode of drill-integration. For github use: githubPullRequestReportByEvent"
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
  env:
    MODE_PARAM: ${{ inputs.mode }}
