name: 'drill4j-report-github-action'
description: 'Report test-coverage by Drill4J'
branding:
  icon: info
  color: blue
inputs:
  api_url:
    description: "Drill4J API URL"
    required: true
  api_key:
    description: "Drill4J API key"
    required: true
  group_id:
    description: "Group ID"
    required: true
  agent_id:
    description: "Agent ID"
    required: true
  github_token:
    description: "Github Token"
    required: true
  mode:
    description: "Mode of drill-integration"
    required: false
    default: "githubPullRequestReportByEvent"
runs:
  using: 'docker'
  image: './Dockerfile'
  env:
    MODE_PARAM: ${{ inputs.mode }}
