name: Check

on:
  push:
    branches:
      - '*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'
  pull_request:
    branches:
      - 'main'
      - 'release/*'
    paths:
      - '**/src/**'
      - '**.gradle.kts'
      - 'gradle.properties'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: corretto
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ${{ github.workspace }}/gradlew
      - run: git config --global user.email "test@test.test"
      - run: git config --global user.name "test"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --stacktrace
