name: Publish
run-name: 'Publish: ${{ github.ref }}'
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: corretto
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ${{ github.workspace }}/gradlew
      - run: git config --global user.email "test@test.test"
      - run: git config --global user.name "test"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check --stacktrace
      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports-${{ matrix.config.preset }}
          path: ${{ github.workspace }}/*/build/reports/*
  publish:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: 8.0
          distribution: corretto
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x ${{ github.workspace }}/gradlew
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
